### PR TITLE
1.17.30/1.18 update

### PR DESCRIPTION
**Pull request by extremeheat**
* Support 3D biomes
* Fix an issue with wrong palette size serialization in SubChunk
* Fix (wrong?) non-cache serialization code that did not include height data

### CODE REVIEW

**Comment by rom1504** [comment]
looks like ci still failing

**Comment by extremeheat** [comment]
needs https://github.com/PrismarineJS/minecraft-data/pull/498

**Comment by rom1504** [comment]
mcdata released

**Comment by extremeheat** [comment]
Passing

**Comment by rom1504** [comment]
There's a conflict

**Comment by extremeheat** [comment]
fixed

**Pull request merged**
